# Data cleaning

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('AutoscootScraper/autoscout24/cars.csv')
df.head()

,url,brand,model,price,first_registration,mileage,fuel_type,color,gearbox,power,...,location,body_type,doors,seats,drivetrain,co2_emission,emission_class,condition,upholstery,upholstery_color
0,https://www.autoscout24.com/offers/alfa-romeo-...,Alfa Romeo,159,"€ 5,500.-",07/2011,"233,685 km",Diesel,Red,Manual,100 kW (136 hp),...,"Terni -Tr, IT",Sedan,4,5,Front,unknown,134 g/km (comb.),Used,Grey,Others
1,https://www.autoscout24.com/offers/alfa-romeo-...,Alfa Romeo,159,"€ 13,990.-",01/2010,"134,000 km",Gasoline,Red,Manual,147 kW (200 hp),...,"EL PRAT DE LLOBREGAT, ES",Sedan,4,5,Front,unknown,unknown,Used,unknown,unknown
2,https://www.autoscout24.com/offers/renault-oth...,Renault,unknown,"€ 2,300.-",07/1963,"27,000 km",Gasoline,Yellow,Manual,59 kW (80 hp),...,"Waregem, BE",Sedan,unknown,unknown,unknown,unknown,unknown,Used,unknown,alcantara
3,https://www.autoscout24.com/offers/opel-antara...,Opel,Antara,"€ 3,499.-",09/2008,"212,575 km",Gasoline,Black,Manual,103 kW (140 hp),...,"WIERDEN, NL",Off-Road/Pick-up,5,5,4WD,unknown,229 g/km (comb.),Used,unknown,Metallic
4,https://www.autoscout24.com/offers/alfa-romeo-...,Alfa Romeo,Giulia,"€ 39,800.-",03/2023,"7,100 km",Gasoline,White,Automatic,206 kW (280 hp),...,"Meckenheim, DE",Sedan,4,4,Front,Euro 6d,unknown,Employee's car,Full leather,Black

In [6]:
# Drop duplicates
df = df.drop_duplicates()

# Clean price column
df['price'] = df['price'].str.replace('€', '')
df['price'] = df['price'].str.replace(',', '')
df['price'] = df['price'].str.replace(' ', '')
df['price'] = df['price'].str.replace('.-', '')
df['price'] = pd.to_numeric(df['price'], errors='coerce') # Clean the unknown in the price column with NaN (Wich pandas recognize)
#df.dropna(subset=['price'], inplace=True) # drop the NaN in the prices #Do we add it here ????? (2 NaN)

# Clean mileage column  
df['mileage'] = df['mileage'].str.replace(' km', '')
df['mileage'] = df['mileage'].str.replace(',', '')
df['mileage'] = df['mileage'].str.replace(' ', '')

# Clean first_registration column
df['first_registration'] = df['first_registration'].str.extract(r'(\d{4})')
# To improve the nulls on the date, we''re giving a cutoff date : 1900-01-01
df['first_registration'] = pd.to_datetime(df['first_registration'])
df['first_registration'] = df['first_registration'].fillna(pd.Timestamp('1900-01-01'))


# Clean power column keeo only horsepower e.g. "100 kW (136 hp)" -> "136"
df['power'] = df['power'].str.extract(r'(\d+)')

# Clean engine_size column
df['engine_size'] = df['engine_size'].str.extract(r'(\d+)')

# Clean location column
df['country'] = df['location'].str.extract(r'(\w+)$')



# Lowercase all strings
df['brand'] = df['brand'].str.lower()
df['model'] = df['model'].str.lower()
df['fuel_type'] = df['fuel_type'].str.lower()
df['color'] = df['color'].str.lower()
df['gearbox'] = df['gearbox'].str.lower()
df['seller']  = df['seller'].str.lower()
df['location'] = df['location'].str.lower()
df['body_type'] = df['body_type'].str.lower()
df['drivetrain'] = df['drivetrain'].str.lower()
df['condition'] = df['condition'].str.lower()
df['upholstery'] = df['upholstery'].str.lower()
df['upholstery_color'] = df['upholstery_color'].str.lower()

# Export cleaned data
df.to_csv('cleaned_cars.csv', index=False)